name: test_task_cards
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ^3.11.5

resolution: workspace

dependencies:
  confetti: ^0.8.0
  dio: ^5.7.0
  equatable: ^2.0.8
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  l: ^5.0.1
  patrol_finders: ^3.6.0
  shared:
    path: ../shared

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  patrol: ^4.7.1
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true

patrol:
  app_name: test_task_cards
  android:
    package_name: com.example.test_task_cards
  ios:
    bundle_id: com.example.testTaskCards
