import 'package:test_task_cards/features/progress/models/progress_model.dart';
import 'package:test_task_cards/core/result.dart';

/// {@template progress_repo}
/// Defines progress data access contract through [ProgressRepo].
/// {@endtemplate}
sealed class ProgressRepo {
  const ProgressRepo();

  /// {@macro progress_repo}
  Future<Result<ProgressModel>> readProgress();
}

/// {@macro progress_repo}
/// REST realization for network-backed progress access.
final class ProgressRepo$Rest extends ProgressRepo {
  const ProgressRepo$Rest() : super();

  @override
  Future<Result<ProgressModel>> readProgress() async {
    throw UnimplementedError();
  }
}

/// {@macro progress_repo}
/// Stub realization for placeholder progress access wiring.
final class ProgressRepo$Stub extends ProgressRepo {
  const ProgressRepo$Stub() : super();

  @override
  Future<Result<ProgressModel>> readProgress() async {
    throw UnimplementedError();
  }
}

// # Generated by Copilot
