import 'package:test_task_cards/features/progress/models/progress_model.dart';
import 'package:test_task_cards/features/cards/models/card_model.dart';
import 'package:test_task_cards/core/result.dart';

typedef CardSwipeChoice = ({CardModel card, bool isRightSwipe});

/// {@template progress_repo}
/// Defines progress data access contract through [ProgressRepo].
/// {@endtemplate}
sealed class ProgressRepo {
  const ProgressRepo();

  /// {@macro progress_repo}
  Future<Result<ProgressModel>> readProgress();

  /// {@macro progress_repo}
  Future<Result<void>> saveCardChoice({required CardModel card, required bool isRightSwipe});

  /// {@macro progress_repo}
  Future<Result<List<CardSwipeChoice>>> loadHistory({int length = 10});
}

/// {@macro progress_repo}
/// REST realization for network-backed progress access.
final class ProgressRepo$Rest extends ProgressRepo {
  const ProgressRepo$Rest() : super();

  @override
  Future<Result<ProgressModel>> readProgress() async {
    throw UnimplementedError();
  }

  @override
  Future<Result<void>> saveCardChoice({required CardModel card, required bool isRightSwipe}) async {
    throw UnimplementedError();
  }

  @override
  Future<Result<List<CardSwipeChoice>>> loadHistory({int length = 10}) async {
    throw UnimplementedError();
  }
}

/// {@macro progress_repo}
/// Stub realization for placeholder progress access wiring.
final class ProgressRepo$Stub extends ProgressRepo {
  const ProgressRepo$Stub() : super();

  static final _history = <CardSwipeChoice>[];

  @override
  Future<Result<ProgressModel>> readProgress() async {
    throw UnimplementedError();
  }

  @override
  Future<Result<void>> saveCardChoice({required CardModel card, required bool isRightSwipe}) async {
    _history.add((card: card.copyWith(), isRightSwipe: isRightSwipe));
    return Result.ok(null);
  }

  @override
  Future<Result<List<CardSwipeChoice>>> loadHistory({int length = 10}) async {
    final limit = length < 0 ? 0 : length;
    if (limit == 0 || _history.isEmpty) {
      return Result.ok(const <CardSwipeChoice>[]);
    }
    final start = _history.length > limit ? _history.length - limit : 0;
    final latest = _history.sublist(start).reversed.toList(growable: false);
    return Result.ok(latest);
  }
}

// # Generated by Copilot
