import 'package:test_task_cards/features/cards/models/card_model.dart';
import 'package:test_task_cards/features/cards/repos/cards_repo.dart';
import 'package:test_task_cards/core/result.dart';

class CardsController {
  CardsController({CardsRepo? repo}) : _repo = repo ?? const CardsRepo$Stub();

  final CardsRepo _repo;

  Future<Result<List<CardModel>>> loadCards() => _repo.loadCards();
}

// # Generated by Copilot
