import 'package:flutter/material.dart';
import 'package:test_task_cards/core/theme_controller.dart';
import 'package:test_task_cards/features/cards/cards.dart';
import 'package:test_task_cards/features/progress/progress.dart';

class HomeScreen extends StatelessWidget {
  const HomeScreen({super.key});

  @override
  Widget build(BuildContext context) {
    final controller = ThemeController.of(context);
    final isDark = Theme.of(context).brightness == Brightness.dark;
    return Scaffold(
      appBar: AppBar(
        actions: [
          IconButton(icon: Icon(isDark ? Icons.light_mode : Icons.dark_mode), onPressed: controller.toggleTheme),
          Builder(
            builder: (context) {
              return IconButton(icon: const Icon(Icons.menu), onPressed: () => Scaffold.of(context).openEndDrawer());
            },
          ),
        ],
      ),
      body: const CardsScreen(),
      endDrawer: const Drawer(
        child: SafeArea(
          child: Padding(padding: EdgeInsets.all(16), child: ProgressView()),
        ),
      ),
    );
  }
}

// # Generated by Copilot
