import 'package:confetti/confetti.dart';
import 'package:flutter/material.dart';

class DeckConfettiBurst extends StatefulWidget {
  const DeckConfettiBurst({
    super.key,
    required this.playTrigger,
    required this.numberOfParticles,
    required this.blastDirection,
  });

  final int playTrigger;
  final int numberOfParticles;
  final double blastDirection;

  @override
  State<DeckConfettiBurst> createState() => _DeckConfettiBurstState();
}

class _DeckConfettiBurstState extends State<DeckConfettiBurst> {
  late final ConfettiController _confettiController;
  late int numberOfParticles = widget.numberOfParticles;

  @override
  void initState() {
    super.initState();
    _confettiController = ConfettiController(duration: const Duration(milliseconds: 900));
  }

  @override
  void didUpdateWidget(covariant DeckConfettiBurst oldWidget) {
    super.didUpdateWidget(oldWidget);
    if (widget.numberOfParticles != oldWidget.numberOfParticles) {
      numberOfParticles = widget.numberOfParticles;
    }
    if (widget.playTrigger != oldWidget.playTrigger && widget.numberOfParticles > 0) {
      _confettiController.play();
    }
  }

  @override
  void dispose() {
    _confettiController.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return ConfettiWidget(
      confettiController: _confettiController,
      blastDirection: widget.blastDirection,
      emissionFrequency: 0.06,
      numberOfParticles: 5,
      maxBlastForce: 22,
      minBlastForce: 10,
      gravity: 0.22,
      shouldLoop: false,
    );
  }
}

// # Generated by Copilot
