import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:test_task_cards/features/cards/controllers/cards_controller.dart';
import 'package:test_task_cards/features/cards/controllers/cards_cubit.dart';
import 'package:test_task_cards/features/cards/repos/cards_repo.dart';

import 'package:test_task_cards/features/cards/widgets/cards_view.dart';

class CardsScreen extends StatelessWidget {
  const CardsScreen({super.key});

  @override
  Widget build(BuildContext context) {
    return BlocProvider(
      create: (_) => CardsCubit(CardsController(repo: const CardsRepo$Stub()))..loadCards(),
      child: const SafeArea(child: CardsView()),
    );
  }
}

// # Generated by Copilot
