import 'package:flutter/material.dart';
import 'package:shared/shared.dart';

class CardTile extends StatelessWidget {
  const CardTile({super.key, required this.card, required this.size});

  final CardModel card;
  final Size size;

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context).textTheme;
    return Container(
      width: size.width,
      height: size.height,
      padding: const EdgeInsets.all(24),
      decoration: BoxDecoration(
        color: Theme.of(context).colorScheme.surface,
        borderRadius: BorderRadius.circular(24),
        border: Border.all(color: Theme.of(context).colorScheme.outlineVariant),
        boxShadow: [BoxShadow(color: Colors.black.withValues(alpha: 0.08), blurRadius: 20, offset: const Offset(0, 8))],
      ),
      child: Column(
        mainAxisAlignment: MainAxisAlignment.center,
        children: [
          Text(card.word, style: theme.headlineMedium),
          const SizedBox(height: 16),
          Text(card.translation, style: theme.headlineSmall),
        ],
      ),
    );
  }
}

// # Generated by Copilot
