import 'dart:async';

import 'package:flutter/material.dart';
import 'package:test_task_cards/widgets/animated_flip_counter.dart';

class StreakCounter extends StatefulWidget {
  const StreakCounter({super.key, required this.streak});

  final int streak;

  @override
  State<StreakCounter> createState() => _StreakCounterState();
}

class _StreakCounterState extends State<StreakCounter> {
  int _lastStreak = 0;
  double _streakScale = 1;
  bool _isStreakHighlighted = false;
  Timer? _streakPulseTimer;

  @override
  void initState() {
    super.initState();
    _lastStreak = widget.streak;
  }

  @override
  void didUpdateWidget(covariant StreakCounter oldWidget) {
    super.didUpdateWidget(oldWidget);
    if (widget.streak > _lastStreak) {
      final targetScale = widget.streak % 10 == 0
          ? 2.0
          : widget.streak % 5 == 0
          ? 1.8
          : 1.35;
      _streakPulseTimer?.cancel();
      setState(() {
        _streakScale = targetScale;
        _isStreakHighlighted = true;
      });
      _streakPulseTimer = Timer(const Duration(milliseconds: 280), () {
        if (!mounted) {
          return;
        }
        setState(() {
          _streakScale = 1;
          _isStreakHighlighted = false;
        });
      });
    }

    if (widget.streak == 0) {
      _streakPulseTimer?.cancel();
      setState(() {
        _streakScale = 1;
        _isStreakHighlighted = false;
      });
    }

    _lastStreak = widget.streak;
  }

  @override
  void dispose() {
    _streakPulseTimer?.cancel();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    final streakStyle = (Theme.of(context).textTheme.headlineLarge ?? const TextStyle(fontSize: 54)).copyWith(
      fontWeight: FontWeight.w700,
      color: _isStreakHighlighted
          ? Theme.of(context).colorScheme.onSecondaryContainer
          : Theme.of(context).colorScheme.onSurface,
    );

    return Column(
      spacing: 16,
      children: [
        Text('Streak', style: Theme.of(context).textTheme.titleLarge),
        SizedBox.square(
          dimension: 80,
          child: Stack(
            alignment: Alignment.center,
            children: [
              TweenAnimationBuilder<double>(
                tween: Tween(end: (widget.streak / 10).clamp(0.0, 1.0)),
                duration: const Duration(milliseconds: 300),
                curve: Curves.easeOutCubic,
                builder: (_, progress, _) {
                  return Transform.flip(
                    flipX: true,
                    child: CircularProgressIndicator(
                      value: progress,
                      strokeCap: StrokeCap.round,
                      strokeWidth: 8,
                      backgroundColor: Colors.grey.withValues(alpha: 0.28),
                      constraints: BoxConstraints.tight(Size.square(56)),
                      valueColor: const AlwaysStoppedAnimation<Color>(Colors.green),
                    ),
                  );
                },
              ),
              Padding(
                padding: const EdgeInsets.fromLTRB(18, 18, 18, 20),
                child: AnimatedDefaultTextStyle(
                  duration: const Duration(milliseconds: 180),
                  curve: Curves.easeOut,
                  style: streakStyle,
                  child: AnimatedScale(
                    duration: const Duration(milliseconds: 180),
                    curve: Curves.easeOutBack,
                    scale: _streakScale,
                    child: AnimatedFlipCounter(
                      value: widget.streak,
                      duration: const Duration(milliseconds: 220),
                      curve: Curves.easeOut,
                    ),
                  ),
                ),
              ),
            ],
          ),
        ),
      ],
    );
  }
}

// # Generated by Copilot
