import 'package:flutter/material.dart';
import 'package:test_task_cards/dependencies.dart';
import 'package:test_task_cards/features/progress/repos/progress_repo.dart';

class ProgressView extends StatelessWidget {
  const ProgressView({super.key});

  @override
  Widget build(BuildContext context) {
    final repo = Dependencies.of(context).repo<ProgressRepo>();
    return FutureBuilder(
      future: repo.loadHistory(),
      builder: (context, snapshot) {
        if (snapshot.connectionState == ConnectionState.waiting) {
          return const Center(child: CircularProgressIndicator());
        }

        if (!snapshot.hasData) {
          return const Center(child: Text('Failed to load history'));
        }

        final result = snapshot.data!;
        return result.when(
          ok: (history) {
            if (history.isEmpty) {
              return const Center(child: Text('No choices yet'));
            }

            return Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Text('Recent choices', style: Theme.of(context).textTheme.titleLarge),
                const SizedBox(height: 12),
                Expanded(
                  child: ListView.separated(
                    itemCount: history.length,
                    separatorBuilder: (_, _) => const Divider(height: 1),
                    itemBuilder: (context, index) {
                      final choice = history[index];
                      final wasCorrect = choice.isRightSwipe == choice.card.isCorrect;
                      return ListTile(
                        contentPadding: EdgeInsets.zero,
                        title: Text('${choice.card.word} -> ${choice.card.translation}'),
                        subtitle: Text(choice.isRightSwipe ? 'Swipe: right' : 'Swipe: left'),
                        trailing: Icon(
                          wasCorrect ? Icons.check_circle : Icons.cancel,
                          color: wasCorrect ? Colors.green : Colors.red,
                        ),
                      );
                    },
                  ),
                ),
              ],
            );
          },
          err: (_, _) => const Center(child: Text('Failed to load history')),
        );
      },
    );
  }
}

// # Generated by Copilot
