import 'package:test_task_cards/features/cards/models/card_model.dart';
import 'package:test_task_cards/core/result.dart';

/// {@template cards_repo}
/// Defines card data access contract through [CardsRepo].
/// {@endtemplate}
sealed class CardsRepo {
  const CardsRepo();

  /// {@macro cards_repo}
  Future<Result<List<CardModel>>> loadCards();
}

/// {@macro cards_repo}
/// REST realization for network-backed card access.
final class CardsRepo$Rest extends CardsRepo {
  const CardsRepo$Rest() : super();

  @override
  Future<Result<List<CardModel>>> loadCards() async {
    throw UnimplementedError();
  }
}

/// {@macro cards_repo}
/// Stub realization for placeholder card access wiring.
final class CardsRepo$Stub extends CardsRepo {
  const CardsRepo$Stub() : super();

  @override
  Future<Result<List<CardModel>>> loadCards() async {
    return Result.ok([
      CardModel.fromJson({'word': 'Doll', 'translation': 'кукла', 'is_correct': true}),
      CardModel.fromJson({'word': 'Ball', 'translation': 'стол', 'is_correct': false}),
      CardModel.fromJson({'word': 'Window', 'translation': 'окно', 'is_correct': true}),
      CardModel.fromJson({'word': 'Chair', 'translation': 'дерево', 'is_correct': false}),
      CardModel.fromJson({'word': 'Book', 'translation': 'книга', 'is_correct': true}),
      CardModel.fromJson({'word': 'Table', 'translation': 'яблоко', 'is_correct': false}),
      CardModel.fromJson({'word': 'Phone', 'translation': 'телефон', 'is_correct': true}),
      CardModel.fromJson({'word': 'River', 'translation': 'река', 'is_correct': true}),
      CardModel.fromJson({'word': 'Bird', 'translation': 'машина', 'is_correct': false}),
      CardModel.fromJson({'word': 'Sun', 'translation': 'солнце', 'is_correct': true}),
      CardModel.fromJson({'word': 'Moon', 'translation': 'луна', 'is_correct': true}),
      CardModel.fromJson({'word': 'Street', 'translation': 'комната', 'is_correct': false}),
      CardModel.fromJson({'word': 'Milk', 'translation': 'молоко', 'is_correct': true}),
      CardModel.fromJson({'word': 'School', 'translation': 'школа', 'is_correct': true}),
      CardModel.fromJson({'word': 'Teacher', 'translation': 'ученик', 'is_correct': false}),
      CardModel.fromJson({'word': 'Garden', 'translation': 'сад', 'is_correct': true}),
      CardModel.fromJson({'word': 'Cloud', 'translation': 'облако', 'is_correct': true}),
      CardModel.fromJson({'word': 'Bread', 'translation': 'карта', 'is_correct': false}),
      CardModel.fromJson({'word': 'Mirror', 'translation': 'зеркало', 'is_correct': true}),
      CardModel.fromJson({'word': 'Bridge', 'translation': 'мост', 'is_correct': true}),
    ]);
  }
}

// # Generated by Copilot
