import 'package:flutter/material.dart';

/// Stores app-wide repositories and shared runtime dependencies.
///
/// Use [init] as the single app-start entry point to register
/// all dependencies required across the app.
class Dependencies {
  /// Single entry point for all app dependency initialization at startup.
  Future<void> init() async {}

  /// Returns a registered dependency by its type.
  T repo<T extends Object>() => _repositories[T]! as T;

  /// Registers a dependency instance under its runtime type.
  @protected
  void putRepo<T extends Object>(covariant T repo) => _repositories[T] = repo;

  /// Returns dependencies from the nearest injected widget scope.
  static Dependencies of(BuildContext context) => InheritedDependencies.of(context).dependencies;

  /// Internal registry for repositories and shared app objects.
  late final _repositories = <Type, Object>{};
}

/// Injects [Dependencies] into the widget tree for descendant access.
class InheritedDependencies extends InheritedWidget {
  const InheritedDependencies({super.key, required this.dependencies, required super.child});

  final Dependencies dependencies;

  static InheritedDependencies of<T extends Dependencies>(BuildContext context) {
    return context.getInheritedWidgetOfExactType<InheritedDependencies>()!;
  }

  @override
  bool updateShouldNotify(InheritedDependencies oldWidget) => oldWidget.dependencies != dependencies;
}

// # Generated by Copilot
