import 'package:flutter/material.dart';
import 'package:test_task_cards/core/theme_controller.dart';
import 'package:test_task_cards/dependencies.dart';
import 'package:test_task_cards/features/home/widgets/home_screen.dart';

Future<void> main() async {
  final deps = Dependencies();
  await deps.init();
  runApp(ThemeController(child: MainApp(deps: deps)));
}

class MainApp extends StatelessWidget {
  const MainApp({super.key, required this.deps});

  final Dependencies deps;

  @override
  Widget build(BuildContext context) {
    final controller = ThemeController.of(context);
    return MaterialApp(
      key: ValueKey(controller.themeMode),
      theme: ThemeData.light(),
      darkTheme: ThemeData.dark(),
      themeMode: controller.themeMode,
      builder: (context, child) => InheritedDependencies(dependencies: deps, child: child!),
      home: const HomeScreen(),
    );
  }
}

// # Generated by Copilot
