import '../../../core/data_class.dart';
import '../../../core/constants.dart';

/// {@template card_model}
/// Immutable vocabulary card record represented by [CardModel].
/// {@endtemplate}
class CardModel extends DataClass<CardModel> {
  /// {@macro card_model}
  const CardModel({required super.json, required this.word, required this.translation, required this.isCorrect});

  final String word, translation;
  final bool isCorrect;

  /// Creates a [CardModel] from serialized data.
  factory CardModel.fromJson(Map<String, Object?> json) {
    return CardModel(
      json: json,
      word: json['word'] as String? ?? '',
      translation: json['translation'] as String? ?? '',
      isCorrect: json['is_correct'] as bool? ?? false,
    );
  }

  @override
  List<Object?> get props => [word, translation, isCorrect];

  /// Returns a new [CardModel] with selected fields replaced.
  @override
  CardModel copyWith({
    Defaulted<String> word = const Omit(),
    Defaulted<String> translation = const Omit(),
    Defaulted<bool> isCorrect = const Omit(),
  }) {
    return CardModel(
      json: json,
      word: word is Omit ? this.word : word as String,
      translation: translation is Omit ? this.translation : translation as String,
      isCorrect: isCorrect is Omit ? this.isCorrect : isCorrect as bool,
    );
  }

  /// Converts this [CardModel] to serialized data.
  @override
  Map<String, Object> toJson() {
    return {'word': word, 'translation': translation, 'is_correct': isCorrect};
  }
}

// # Generated by Copilot
