import 'package:test_task_cards/features/progress/models/progress_model.dart';
import 'package:test_task_cards/features/progress/repos/progress_repo.dart';
import 'package:test_task_cards/core/result.dart';

class ProgressController {
  ProgressController({ProgressRepo? repo}) : _repo = repo ?? const ProgressRepo$Stub();

  final ProgressRepo _repo;

  Future<Result<ProgressModel>> readProgress() => _repo.readProgress();
}

// # Generated by Copilot
