import 'package:flutter/material.dart';

class ThemeController extends StatefulWidget {
  const ThemeController({super.key, required this.child});

  final Widget child;

  static _ThemeControllerInherited of(BuildContext context) {
    return context.dependOnInheritedWidgetOfExactType<_ThemeControllerInherited>()!;
  }

  @override
  State<ThemeController> createState() => ThemeControllerState();
}

class ThemeControllerState extends State<ThemeController> {
  ThemeMode _themeMode = ThemeMode.light;

  ThemeMode get themeMode => _themeMode;

  void toggleTheme() {
    setState(() {
      _themeMode = switch (_themeMode) {
        ThemeMode.dark => ThemeMode.light,
        ThemeMode.light || ThemeMode.system => ThemeMode.dark,
      };
    });
  }

  @override
  Widget build(BuildContext context) {
    return _ThemeControllerInherited(themeMode: themeMode, toggleTheme: toggleTheme, child: widget.child);
  }
}

class _ThemeControllerInherited extends InheritedWidget {
  const _ThemeControllerInherited({required this.themeMode, required this.toggleTheme, required super.child});

  final ThemeMode themeMode;
  final VoidCallback toggleTheme;

  @override
  bool updateShouldNotify(_ThemeControllerInherited oldWidget) {
    return oldWidget.themeMode != themeMode;
  }
}

// # Generated by Copilot
