import 'package:shared/shared.dart';
import 'package:test_task_cards/features/progress/models/progress_model.dart';
import 'package:test_task_cards/core/result.dart';

typedef CardSwipeChoice = ({CardModel card, bool isRightSwipe});

/// {@template progress_repo}
/// Defines progress data access contract through [ProgressRepo].
/// {@endtemplate}
sealed class ProgressRepo {
  const ProgressRepo();

  /// {@macro progress_repo}
  Future<Result<ProgressModel>> readProgress();

  /// {@macro progress_repo}
  Future<Result<void>> saveCardChoice({required CardModel card, required bool isRightSwipe});

  /// {@macro progress_repo}
  Future<Result<void>> resetCurrentStreak();

  /// {@macro progress_repo}
  Future<Result<List<CardSwipeChoice>>> loadHistory({int length = 10});
}

/// {@macro progress_repo}
/// REST realization for network-backed progress access.
final class ProgressRepo$Rest extends ProgressRepo {
  const ProgressRepo$Rest() : super();

  @override
  Future<Result<ProgressModel>> readProgress() async {
    throw UnimplementedError();
  }

  @override
  Future<Result<void>> saveCardChoice({required CardModel card, required bool isRightSwipe}) async {
    throw UnimplementedError();
  }

  @override
  Future<Result<void>> resetCurrentStreak() async {
    throw UnimplementedError();
  }

  @override
  Future<Result<List<CardSwipeChoice>>> loadHistory({int length = 10}) async {
    throw UnimplementedError();
  }
}

/// {@macro progress_repo}
/// Stub realization for placeholder progress access wiring.
final class ProgressRepo$Stub extends ProgressRepo {
  const ProgressRepo$Stub() : super();

  static final _history = <CardSwipeChoice>[];
  static ProgressModel _progress = const ProgressModel(
    json: null,
    currentStreak: 0,
    bestStreak: 0,
    correctCount: 0,
    incorrectCount: 0,
  );

  @override
  Future<Result<ProgressModel>> readProgress() async {
    return Result.ok(_progress);
  }

  @override
  Future<Result<void>> saveCardChoice({required CardModel card, required bool isRightSwipe}) async {
    _history.add((card: card.copyWith(), isRightSwipe: isRightSwipe));
    final isCorrectAnswer = isRightSwipe == card.isCorrect;
    final nextCurrentStreak = isCorrectAnswer ? _progress.currentStreak + 1 : 0;
    final nextBestStreak = nextCurrentStreak > _progress.bestStreak ? nextCurrentStreak : _progress.bestStreak;
    _progress = _progress.copyWith(
      currentStreak: nextCurrentStreak,
      bestStreak: nextBestStreak,
      correctCount: isCorrectAnswer ? _progress.correctCount + 1 : _progress.correctCount,
      incorrectCount: isCorrectAnswer ? _progress.incorrectCount : _progress.incorrectCount + 1,
    );
    return Result.ok(null);
  }

  @override
  Future<Result<void>> resetCurrentStreak() async {
    _progress = _progress.copyWith(currentStreak: 0);
    return Result.ok(null);
  }

  @override
  Future<Result<List<CardSwipeChoice>>> loadHistory({int length = 10}) async {
    final limit = length < 0 ? 0 : length;
    if (limit == 0 || _history.isEmpty) {
      return Result.ok(const <CardSwipeChoice>[]);
    }
    final start = _history.length > limit ? _history.length - limit : 0;
    final latest = _history.sublist(start).reversed.toList(growable: false);
    return Result.ok(latest);
  }
}

// # Generated by Copilot
