import 'package:test_task_cards/core/constants.dart';
import 'package:test_task_cards/core/data_class.dart';

/// {@template progress_model}
/// Immutable session progress snapshot represented by [ProgressModel].
/// {@endtemplate}
class ProgressModel extends DataClass<ProgressModel> {
  /// {@macro progress_model}
  const ProgressModel({
    required super.json,
    required this.currentStreak,
    required this.bestStreak,
    required this.correctCount,
    required this.incorrectCount,
  });

  final int currentStreak, bestStreak, correctCount, incorrectCount;

  /// Creates a [ProgressModel] from serialized data.
  factory ProgressModel.fromJson(Map<String, Object?> json) {
    return ProgressModel(
      json: json,
      currentStreak: json['current_streak'] as int? ?? 0,
      bestStreak: json['best_streak'] as int? ?? 0,
      correctCount: json['correct_count'] as int? ?? 0,
      incorrectCount: json['incorrect_count'] as int? ?? 0,
    );
  }

  @override
  List<Object?> get props => [currentStreak, bestStreak, correctCount, incorrectCount];

  /// Computes the current session accuracy ratio.
  double get accuracy {
    final total = correctCount + incorrectCount;
    return total == 0 ? 0 : correctCount / total;
  }

  /// Returns a new [ProgressModel] with selected fields replaced.
  @override
  ProgressModel copyWith({
    Defaulted<int> currentStreak = const Omit(),
    Defaulted<int> bestStreak = const Omit(),
    Defaulted<int> correctCount = const Omit(),
    Defaulted<int> incorrectCount = const Omit(),
  }) {
    return ProgressModel(
      json: json,
      currentStreak: currentStreak is Omit ? this.currentStreak : currentStreak as int,
      bestStreak: bestStreak is Omit ? this.bestStreak : bestStreak as int,
      correctCount: correctCount is Omit ? this.correctCount : correctCount as int,
      incorrectCount: incorrectCount is Omit ? this.incorrectCount : incorrectCount as int,
    );
  }

  /// Converts this [ProgressModel] to serialized data.
  @override
  Map<String, Object> toJson() {
    return {
      'current_streak': currentStreak,
      'best_streak': bestStreak,
      'correct_count': correctCount,
      'incorrect_count': incorrectCount,
    };
  }
}

// # Generated by Copilot
