import 'dart:math';

import 'package:dart_frog/dart_frog.dart';
import 'package:shared/shared.dart';

final _random = Random();

const _cards = <CardModel>[
  CardModel(json: null, word: 'Doll', translation: 'кукла', isCorrect: true),
  CardModel(json: null, word: 'Ball', translation: 'стол', isCorrect: false),
  CardModel(json: null, word: 'Window', translation: 'окно', isCorrect: true),
  CardModel(json: null, word: 'Chair', translation: 'дерево', isCorrect: false),
  CardModel(json: null, word: 'Book', translation: 'книга', isCorrect: true),
  CardModel(json: null, word: 'Table', translation: 'яблоко', isCorrect: false),
  CardModel(json: null, word: 'Phone', translation: 'телефон', isCorrect: true),
  CardModel(json: null, word: 'River', translation: 'река', isCorrect: true),
  CardModel(json: null, word: 'Bird', translation: 'машина', isCorrect: false),
  CardModel(json: null, word: 'Sun', translation: 'солнце', isCorrect: true),
  CardModel(json: null, word: 'Moon', translation: 'луна', isCorrect: true),
  CardModel(
    json: null,
    word: 'Street',
    translation: 'комната',
    isCorrect: false,
  ),
  CardModel(json: null, word: 'Milk', translation: 'молоко', isCorrect: true),
  CardModel(json: null, word: 'School', translation: 'школа', isCorrect: true),
  CardModel(
    json: null,
    word: 'Teacher',
    translation: 'ученик',
    isCorrect: false,
  ),
  CardModel(json: null, word: 'Garden', translation: 'сад', isCorrect: true),
  CardModel(json: null, word: 'Cloud', translation: 'облако', isCorrect: true),
  CardModel(json: null, word: 'Bread', translation: 'карта', isCorrect: false),
  CardModel(
    json: null,
    word: 'Mirror',
    translation: 'зеркало',
    isCorrect: true,
  ),
  CardModel(json: null, word: 'Bridge', translation: 'мост', isCorrect: true),
  CardModel(json: null, word: 'Forest', translation: 'лес', isCorrect: true),
  CardModel(json: null, word: 'Engine', translation: 'обед', isCorrect: false),
  CardModel(
    json: null,
    word: 'Bottle',
    translation: 'бутылка',
    isCorrect: true,
  ),
  CardModel(json: null, word: 'Rocket', translation: 'ракета', isCorrect: true),
];

Response onRequest(RequestContext context) {
  final shuffled = List.of(_cards)..shuffle(_random);
  final selected = shuffled.take(10).toList(growable: false);
  return Response.json(body: selected.map((c) => c.toJson()).toList());
}

// # Generated by Copilot
